services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_INTERNAL_URL=http://backend:9000
      # - NEXT_PUBLIC_API_URL=https://4fe5-2a02-ab88-278f-d800-100f-3c00-9829-2918.ngrok-free.app
      - NEXT_PUBLIC_API_URL=http://localhost:9000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/next.config.ts:/app/next.config.ts
    depends_on:
      backend:
        condition: service_started

  backend:
    build: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend/storage:/app/storage
      - ./backend/app:/app/app
    environment:
      - AUDIOBOOK_REDIS_URL=redis://redis:6379
      - AUDIOBOOK_DATABASE_URL=postgresql+asyncpg://audiobook:audiobook_dev@postgres:5432/audiobook
      - AUDIOBOOK_STORAGE_PATH=/app/storage
      - AUDIOBOOK_CORS_ORIGINS=*
      - AUDIOBOOK_OLLAMA_URL=http://host.docker.internal:11434
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    volumes:
      - ./backend/storage:/app/storage
      - ./backend/app:/app/app
    environment:
      - AUDIOBOOK_REDIS_URL=redis://redis:6379
      - AUDIOBOOK_DATABASE_URL=postgresql+asyncpg://audiobook:audiobook_dev@postgres:5432/audiobook
      - AUDIOBOOK_STORAGE_PATH=/app/storage
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: audiobook
      POSTGRES_PASSWORD: audiobook_dev
      POSTGRES_DB: audiobook
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audiobook"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
